version: "3"

services:
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    hostname: nexus.trustchain.com
    privileged: true
    dns:
      - 172.31.0.254
    volumes:
     - /srv/nexus-data:/nexus-data

  nginx:
    image: nginx
    container_name: nginx
    dns:
      - 172.31.0.254
    privileged: true
    ports:
      - "80:80"
    volumes:
      - ./nginx_conf.d:/etc/nginx/conf.d

  registry:
    image: registry:2
    container_name: registry
    ports:
      - 5000:5000
    environment:
      - REGISTRY_PROXY_REMOTEURL="https://docker.mirrors.ustc.edu.cn"
    volumes:
      - /srv/registry:/var/lib/registry
