version: '3'

services:
  gerrit:
    image: gerritcodereview/gerrit:2.14.8
    container_name: gerrit
    hostname: gerrit.example.com
    privileged: true
    dns:
      - 172.31.0.254
    ports:
      - "29418:29418"
      - "80:8080"
#    user: 0:0
    depends_on:
      - postgres
    volumes:
     - /srv/gerrit/etc:/var/gerrit/etc
     - /srv/gerrit/git:/var/gerrit/git
     - /srv/gerrit/index:/var/gerrit/index
     - /srv/gerrit/cache:/var/gerrit/cache
    #entrypoint: java -jar /var/gerrit/bin/gerrit.war init -d /var/gerrit

  postgres:
    image: postgres:9.6
    container_name: postgres
    environment:
      - POSTGRES_USER=gerrit
      - POSTGRES_PASSWORD=gerrit
      - POSTGRES_DB=reviewdb
    volumes:
      - /srv/postgres:/var/lib/postgresql/data
