version: '3.7'

services:
  nginx:
    image: nginx
    container_name: nginx
    hostname: nginx
    networks:
      - devops
#   dns:
#     - 192.168.6.114
    privileged: true
    ports:
      - "80:80"
#     - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/www:/var/www
#     - ./nginx/ssl:/etc/nginx/ssl

networks:
  devops:
    name: devops
